export const CONFIG =
{
  USER_PROFILE:
  {
    MINIMUM_AGE: 13,
    MAXIMUM_AGE: 70,
    DEFAULT_AGE: 18,
    RADIUS_IN_MILES: 25
  },
  CAREER_GOAL:
  {
    DEFAULT_RETIREMENT_AGE: 65,
    RETIREMENT_AGE_MINIMUM: 40,
    RETIREMENT_AGE_MAXIMUM: 80,
  },
  EDUCATION_COST:
  {
    YEARS_TO_COMPLETE_MINIMUM: 1,
    YEARS_TO_COMPLETE_DEFAULT: 4,
    YEARS_TO_COMPLETE_MAXIMUM: 8,
    YEARS_OF_COLLEGE_HIGH_SCHOOL: 0,
    YEARS_OF_COLLEGE_ASSOCIATES_DEGREE: 2,
    YEARS_OF_COLLEGE_BACHELORS_DEGREE: 4,
    YEARS_OF_COLLEGE_MASTERS_DEGREE: 6,
    YEARS_OF_COLLEGE_DOCTORATE_DEGREE: 8
  },
  EDUCATION_FINANCING:
  {
    MAXIMUM_FEDERAL_LOAN_AMOUNT: 31000,
    PAY_OFF_LOAN_MINIMUM_IN_YEARS: 0,
    PAY_OFF_LOAN_MAXIMUM_IN_YEARS: 30,
    DEFAULT_PAY_OFF_FEDERAL_LOAN_IN_YEARS: 10,
    DEFAULT_PAY_OFF_PRIVATE_LOAN_IN_YEARS: 8,
  }
};
